CREATE TABLE IF NOT EXISTS orders (
   id INTEGER PRIMARY KEY,
   product_id INTEGER REFERENCES products (id) NOT NULL,
   quantity INTEGER NOT NULL,
   user_id INTEGER REFERENCES users (id) NOT NULL,
   status VARCHAR(150) NOT NULL
);